# Generated by Django 4.2 on 2025-11-28 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='对话会话的标题（可选）', max_length=200, null=True, verbose_name='会话标题')),
                ('mode', models.CharField(choices=[('single', '单次问答'), ('multi', '多轮对话')], default='multi', help_text='单次问答：每次独立；多轮对话：保留历史', max_length=10, verbose_name='对话模式')),
                ('model_used', models.CharField(default='gemini-3-pro-preview', help_text='该会话使用的AI模型名称', max_length=100, verbose_name='使用的模型')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='会话创建的时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最后更新的时间', verbose_name='更新时间')),
                ('user', models.ForeignKey(blank=True, help_text='创建该会话的用户（可选）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '对话会话',
                'verbose_name_plural': '对话会话',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', '助手'), ('system', '系统')], help_text='消息的发送者角色', max_length=10, verbose_name='消息角色')),
                ('content', models.TextField(help_text='消息的文本内容', verbose_name='消息内容')),
                ('prompt_tokens', models.IntegerField(blank=True, help_text='本次请求消耗的提示词Token数量', null=True, verbose_name='提示词Token数')),
                ('completion_tokens', models.IntegerField(blank=True, help_text='本次响应消耗的完成Token数量', null=True, verbose_name='完成Token数')),
                ('total_tokens', models.IntegerField(blank=True, help_text='本次请求消耗的总Token数量', null=True, verbose_name='总Token数')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='消息创建的时间', verbose_name='创建时间')),
                ('conversation', models.ForeignKey(help_text='该消息所属的对话会话', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation', verbose_name='所属会话')),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息',
                'ordering': ['conversation', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='chat_messag_convers_3154fc_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['role'], name='chat_messag_role_9cd150_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', 'updated_at'], name='chat_conver_user_id_6e2bb0_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['mode'], name='chat_conver_mode_ba9e51_idx'),
        ),
    ]
