# Generated by Django 4.2 on 2025-11-28 04:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField(help_text='从该帧中识别出的文字内容', verbose_name='识别文字')),
                ('confidence', models.FloatField(blank=True, help_text='OCR识别的置信度（0-1之间）', null=True, verbose_name='置信度')),
                ('model_used', models.CharField(blank=True, help_text='用于OCR识别的AI模型名称', max_length=100, null=True, verbose_name='使用的模型')),
                ('processing_time', models.FloatField(blank=True, help_text='OCR处理所花费的时间', null=True, verbose_name='处理时间（秒）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'OCR识别结果',
                'verbose_name_plural': 'OCR识别结果',
                'ordering': ['frame__video', 'frame__timestamp'],
            },
        ),
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='视频文件的标题或名称', max_length=200, verbose_name='视频标题')),
                ('video_file', models.FileField(help_text='上传的视频文件（支持mp4, avi, mov, mkv, webm格式）', upload_to='uploaded_videos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'mkv', 'webm'])], verbose_name='视频文件')),
                ('file_size', models.BigIntegerField(help_text='视频文件的大小，单位：字节', verbose_name='文件大小（字节）')),
                ('duration', models.FloatField(blank=True, help_text='视频的时长，单位：秒', null=True, verbose_name='视频时长（秒）')),
                ('resolution', models.CharField(blank=True, help_text='视频分辨率，格式：宽x高（如：1920x1080）', max_length=20, null=True, verbose_name='分辨率')),
                ('status', models.CharField(choices=[('uploaded', '已上传'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '处理失败')], default='uploaded', help_text='视频处理的当前状态', max_length=20, verbose_name='处理状态')),
                ('error_message', models.TextField(blank=True, help_text='如果处理失败，存储错误信息', null=True, verbose_name='错误信息')),
                ('ocr_text_summary', models.TextField(blank=True, help_text='从视频中提取的所有文字内容的合并结果', null=True, verbose_name='OCR文字摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='视频上传的时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最后更新的时间', verbose_name='更新时间')),
                ('processed_at', models.DateTimeField(blank=True, help_text='OCR处理完成的时间', null=True, verbose_name='处理完成时间')),
            ],
            options={
                'verbose_name': '视频文件',
                'verbose_name_plural': '视频文件',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_number', models.IntegerField(help_text='帧在视频中的序号', verbose_name='帧序号')),
                ('timestamp', models.FloatField(help_text='该帧在视频中的时间位置，单位：秒', verbose_name='时间戳（秒）')),
                ('frame_image', models.ImageField(help_text='提取的帧图像文件', upload_to='frames/%Y/%m/%d/', verbose_name='帧图像')),
                ('extraction_method', models.CharField(default='scene_detection', help_text='帧提取的方法（scene_detection: 场景检测, fixed_interval: 固定间隔）', max_length=50, verbose_name='提取方法')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('video', models.ForeignKey(help_text='该帧所属的视频文件', on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='video.videofile', verbose_name='所属视频')),
            ],
            options={
                'verbose_name': '视频帧',
                'verbose_name_plural': '视频帧',
                'ordering': ['video', 'timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='videofile',
            index=models.Index(fields=['status', 'created_at'], name='video_video_status_502f1b_idx'),
        ),
        migrations.AddField(
            model_name='ocrresult',
            name='frame',
            field=models.OneToOneField(help_text='该OCR结果对应的视频帧', on_delete=django.db.models.deletion.CASCADE, related_name='ocr_result', to='video.videoframe', verbose_name='所属帧'),
        ),
        migrations.AddIndex(
            model_name='videoframe',
            index=models.Index(fields=['video', 'timestamp'], name='video_video_video_i_a5498a_idx'),
        ),
        migrations.AddIndex(
            model_name='ocrresult',
            index=models.Index(fields=['frame'], name='video_ocrre_frame_i_f8946b_idx'),
        ),
    ]
